import Link from 'next/link'

export default function AboutPage() {
  return (
    <main className="min-h-screen flex flex-col">
      <nav className="flex items-center justify-between px-6 py-5 border-b border-zinc-800/50">
        <Link href="/" className="font-bold text-lg tracking-tight">DoWeMatch</Link>
      </nav>

      <div className="flex-1 px-6 py-12 max-w-2xl mx-auto w-full prose prose-invert prose-sm max-w-none
        prose-headings:font-bold prose-headings:text-zinc-100
        prose-p:text-zinc-400 prose-p:leading-relaxed
        prose-a:text-violet-400 prose-a:no-underline hover:prose-a:text-violet-300">

        <h1>About DoWeMatch</h1>

        <p>
          DoWeMatch is a two-sided compatibility reveal tool. Two people answer the same
          10 questions independently, and an AI generates a single, specific report about
          both of them together.
        </p>

        <p>
          The point isn&apos;t the score. The point is what happens when you compare honest
          answers — things you might not have said directly, but would say anonymously.
        </p>

        <h2>Why we built this</h2>

        <p>
          Most compatibility tools ask one person to answer for two. That introduces bias
          immediately — you answer how you think your partner would respond, filtered through
          what you want the result to be.
        </p>

        <p>
          We built DoWeMatch so both people answer separately, without knowing what the other
          said. The AI sees both sets of answers at once and writes a report that&apos;s specific
          to those two people — not a generic label based on a score bucket.
        </p>

        <h2>Who it&apos;s for</h2>

        <p>
          Couples who want a starting point for conversations they&apos;ve been avoiding.
          Friends who want to know where they actually stand. People in situationships who
          know someone needs to say something but neither one has said it yet.
        </p>

        <h2>The AI</h2>

        <p>
          Reports are generated by a large language model (Llama 3.3 via Groq). The AI is
          prompted to be specific and honest, not generic or flattering. Results will vary —
          they reflect the actual answers given, not a predetermined compatibility category.
        </p>

        <p>
          We don&apos;t store personal information. Sessions expire after 7 days.
        </p>

        <h2>Contact</h2>

        <p>
          For questions or feedback, reach out through our{' '}
          <Link href="/privacy">privacy page</Link>.
        </p>
      </div>

      <footer className="border-t border-zinc-800/50 px-6 py-6 text-center text-xs text-zinc-600">
        <Link href="/" className="hover:text-zinc-400 transition">DoWeMatch</Link> &mdash;{' '}
        <Link href="/privacy" className="hover:text-zinc-400 transition">Privacy</Link> &bull;{' '}
        <Link href="/terms" className="hover:text-zinc-400 transition">Terms</Link>
      </footer>
    </main>
  )
}
