import Link from 'next/link'

export default function TermsPage() {
  return (
    <main className="min-h-screen flex flex-col">
      <nav className="flex items-center justify-between px-6 py-5 border-b border-zinc-800/50">
        <Link href="/" className="font-bold text-lg tracking-tight">DoWeMatch</Link>
      </nav>

      <div className="flex-1 px-6 py-12 max-w-2xl mx-auto w-full prose prose-invert prose-sm max-w-none
        prose-headings:font-bold prose-headings:text-zinc-100
        prose-p:text-zinc-400 prose-p:leading-relaxed">

        <h1>Terms of Service</h1>
        <p className="text-zinc-600 text-xs">Last updated: January 2025</p>

        <h2>Using DoWeMatch</h2>
        <p>
          DoWeMatch is a free compatibility tool. By using it, you agree to these terms.
          If you don&apos;t agree, please don&apos;t use the service.
        </p>

        <h2>What DoWeMatch is</h2>
        <p>
          DoWeMatch generates AI-based compatibility reports for entertainment and
          self-reflection purposes. Results are generated by a language model and should
          not be treated as professional relationship advice, psychological assessment,
          or a clinical evaluation of any kind.
        </p>
        <p>
          The AI report reflects patterns in the answers given. It does not account for
          context, history, nuance, or anything outside of those 10 questions.
        </p>

        <h2>What you agree to</h2>
        <ul>
          <li>You will not use DoWeMatch to harass, manipulate, or harm another person.</li>
          <li>You will not attempt to reverse-engineer, overload, or abuse the service.</li>
          <li>You understand that results are generated by AI and are not guarantees.</li>
          <li>You are at least 13 years old to use this service.</li>
        </ul>

        <h2>Limitations</h2>
        <p>
          DoWeMatch is provided &quot;as is.&quot; We make no warranties about accuracy,
          availability, or fitness for any particular purpose. We are not responsible for
          decisions made based on DoWeMatch results.
        </p>
        <p>
          We reserve the right to modify or discontinue the service at any time without notice.
        </p>

        <h2>AI-generated content</h2>
        <p>
          Reports are generated by a third-party AI model (Llama 3.3 via Groq). AI outputs
          can be unpredictable. If a result seems inaccurate or offensive, please understand
          that it reflects pattern-matching on the given answers, not human judgment.
        </p>

        <h2>Governing law</h2>
        <p>
          These terms are governed by applicable laws. Any disputes will be resolved
          through good-faith discussion before any legal action.
        </p>
      </div>

      <footer className="border-t border-zinc-800/50 px-6 py-6 text-center text-xs text-zinc-600">
        <Link href="/" className="hover:text-zinc-400 transition">DoWeMatch</Link> &mdash;{' '}
        <Link href="/privacy" className="hover:text-zinc-400 transition">Privacy</Link>
      </footer>
    </main>
  )
}
